<?php
/**
 * CoullWorks Catalog Infinite Scroll for Magento 2.
 *
 * @author    danrcoull <ttechitsolutions@gmail.com>
 * @copyright Copyright (c) 2020-2026 CoullWorks
 * @license   MIT
 * @link      https://github.com/CoullWorks/magento2-catalog-infinite-scroll
 */

declare(strict_types=1);

use CoullWorks\CatalogInfiniteScroll\Block\Scroll;
use Magento\Framework\Escaper;

/** @var Scroll $block */
/** @var Escaper $escaper */
?>
<script id="coullworks-scroll-status" type="text/x-magento-template">
    <div class="page-load-status cw-infinite-scroll__status">
        <div class="infinite-scroll-request">
            <div class="loader-ellips" aria-hidden="true">
                <span class="loader-ellips__dot"></span>
                <span class="loader-ellips__dot"></span>
                <span class="loader-ellips__dot"></span>
                <span class="loader-ellips__dot"></span>
            </div>
        </div>
        <p class="infinite-scroll-last"><%- data.text %></p>
        <p class="infinite-scroll-error"><%- data.text %></p>
    </div>
    <div class="actions cw-infinite-scroll__more">
        <button type="button" class="action primary view-more-button">
            <?= $escaper->escapeHtml(__('View More')) ?>
        </button>
    </div>
</script>
<script type="text/x-magento-init">
    <?= /* @noEscape */ $block->getInitJson() ?>
</script>
